from frappe.custom.doctype.custom_field.custom_field import create_custom_fields
import frappe

def after_install():
    shipment_form = dict(
        title="Shipment Form",
        route="shipment-form",
        published=1,
        doc_type="Shipment Form",
        module="ERPNext Shipping",
        is_standard= 0,
        login_required= 1,
        allow_multiple= 0,
        allow_edit=1,
        allow_delete=0,
        anonymous=0,
        allow_comments=0,
        show_attachments=0,
        allow_incomplete=0,
        max_attachment_size=0,
        show_list=1,
        show_sidebar=0,
        button_label="Зберегти",
        success_title="Return to Cart",
        success_url="/cart",
        client_script="""\nfrappe.web_form.after_load = () => {\n    if (window.location.pathname.endsWith(\"/new\") && frappe.session.user) {\n        frappe.web_form.set_value('full_name', frappe.session.user)\n    }\n}\n\nfrappe.web_form.on('city', (field, value) => {\n    if (value) {\n        frappe.call({\n                method: 'frappe.client.get_list',\n                args: {\n                    doctype: 'NovaPoshta Warehouse',\n                    fields: ['ref as value', 'warehouse_name as label'],\n                    filters: {\n                        'city': value\n                    },\n                    limit_page_length: 2048,\n                    order_by: 'warehouse_name asc'\n                },\n                callback: function(data) {\n                    if (data.message) {\n                        frappe.web_form.fields_dict.warehouse.set_data(data.message);\n                    }\n                }\n            });\n    }\n    \n});""",
        doctype="Web Form",
        web_form_fields=[
            dict(
                fieldname="full_name",
                fieldtype="Data",
                label="Full Name",
                idx=1,
                allow_read_on_all_link_options=0,
                read_only=0,
                show_in_filter=0,
                hidden=0,
                max_length=0,
                max_value=0,
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            ),
            dict(
                fieldname="payment_method",
                fieldtype="Link",
                idx=2,
                label="Payment method",
                allow_read_on_all_link_options=1,
                reqd=0,
                read_only=0,
                show_in_filter=0,
                hidden=0,
                options="Payment Methods",
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            ),
            dict(
                fieldtype="Column Break",
                idx=3,
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            ),
            dict(
                idx= 4,
                fieldname="phone",
                fieldtype="Data",
                label="Phone",
                allow_read_on_all_link_options=0,
                reqd=1,
                read_only=0,
                show_in_filter=0,
                hidden=0,
                options="Phone",
                max_length=20,
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            ),
            dict(
                idx= 5,
                fieldname="email",
                fieldtype="Data",
                label="Email",
                allow_read_on_all_link_options=0,
                reqd=1,
                read_only=0,
                show_in_filter=0,
                hidden=0,
                options="Email",
                max_length=0,
                max_value=0,
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            ),
            dict(
                idx=6,
                fieldtype="Section Break",
                label="Shipping Address",
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            ),
            dict(
                idx= 7,
                fieldname="provider",
                fieldtype="Select",
                label="Shipment Provider",
                allow_read_on_all_link_options= 1,
                reqd= 1,
                read_only= 1,
                hidden=0,
                options="NovaPoshta",
                max_length=0,
                max_value=0,
                default="NovaPoshta",
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            ),
            dict(
                idx= 8,
                fieldname="city",
                fieldtype="Link",
                label="City",
                allow_read_on_all_link_options=1,
                reqd=1,
                read_only=0,
                show_in_filter=0,
                hidden=0,
                options="NovaPoshta cities",
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            ),
            dict(
                idx= 9,
                fieldname="warehouse",
                fieldtype="Link",
                label="Warehouse",
                allow_read_on_all_link_options=1,
                reqd=1,
                read_only=0,
                show_in_filter=0,
                hidden=0,
                options="NovaPoshta Warehouse",
                parent="shipment-form",
                parentfield="web_form_fields",
                parenttype="Web Form",
                doctype="Web Form Field"
            )
        ])
    form = frappe.get_doc(shipment_form)
    form.save()